### ISSUE TITLE
Improve the UI of the About section button

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#25]
![img1](https://github.com/HimanshuNarware/Devlabs/assets/83147410/21d0305d-cb55-4f14-af62-163ff51bab43)
![img2](https://github.com/HimanshuNarware/Devlabs/assets/83147410/27e90a6a-6186-47aa-920d-3a3145189285)

**Comment by aman4uas** [comment]
Hey @HimanshuNarware !! 
Can you please assign this to me?

**Comment by HimanshuNarware** [comment]
@aman4uas  assigned you

**Comment by Jagdeep30** [comment]
Is it open ?

**Comment by HimanshuNarware** [comment]
> Is it open ?

@Jagdeep30 it's already assigned

**Comment by Mridul2820** [comment]
Is it Still Open? 
I can change the button with some good styles
Can you assign it to me?

**Comment by aman4uas** [comment]
Thanks @HimanshuNarware  I will be raising PR within 3-4 days !!

You can search for my username and assign me the task in the assignees option in the top right corner of this page so that anyone reaching out to this issue gets to know that its assigned...


![image](https://github.com/HimanshuNarware/Devlabs/assets/96907045/c8c66866-f73c-419f-bdee-f8cfcfcd6b6d)
