### ISSUE TITLE
"Back to Top" Arrow to Side of Screen While Scrolling

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#395]
The "**_Back to Top"_** arrow should be visible on the side of the screen as the user scrolls down, allowing for quick access to return to the top of the page.
This improvement will enhance navigation and user experience by providing a quick and easy way to return to the top of the page.

### **_Like This_**

https://github.com/HimanshuNarware/Devlabs/assets/140513098/1c2e62f4-523d-4e6b-a51e-55c79fec6baf

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by tanisha11do** [comment]
Project owner, please label this issue so that I can work on resolving it promptly. I would appreciate it if you could assign this task to me. Thank you..

☑️ I have checked the existing issues *
☑️ I have read the Contributing Guidelines *
☑️ I have starred the repository *
☑️ Working under Gssoc'24
