### ISSUE TITLE
Email icon is not working

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#62]
![Screenshot 2023-10-07 201552](https://github.com/HimanshuNarware/Devlabs/assets/83147410/af412084-1c4f-477f-9197-024bdf2332a1)

**Comment by techfreakSahil** [comment]
Hello @HimanshuNarware,
I would like to work on this issue. Please assign me this.
Thank you.

**Comment by HimanshuNarware** [comment]
@techfreakSahil Assigned you

**Comment by techfreakSahil** [comment]
So the mail icon is working.
It worked correct with the mobile version.
Some people might be facing problem with the pc version because their default email service is not set to there default browser or a specific email service.(No actual problem with the code) We can update the readme.me for users to let them know how to configure this if they are facing it.

Here is a stackoverflow link in how to make it work -
[https://stackoverflow.com/questions/34129707/href-mailto-is-not-working-on-any-of-the-browsers](url)
After setting my email service its working now -
![Screenshot (2)](https://github.com/HimanshuNarware/Devlabs/assets/116283802/6dbbb9d9-951c-4904-8e2b-a7fe063e79cc)
