### ISSUE TITLE
Add share button on the Content box

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#7]
Description 
Add a share button on the content box, so that users can share the link directly with another user

**Comment by Rawshansharma** [comment]
Hey @HimanshuNarware Maybe i could help with this issue Can you assign it to me.

**Comment by shreyanshtiwari02** [comment]
Hi,
By content do you mean to add the share button here?

![image](https://github.com/HimanshuNarware/Devlabs/assets/81490172/74755755-d04d-47d0-b2e7-bb8ec43f7c2e)

Can you please provide details about the share button? 
Is it there so that the content link gets copied to the clipboard of the user?

Thank You

**Comment by shreyanshtiwari02** [comment]
Hi,
I have added a Share button which when clicked shows an alert saying Link Copied!
![image](https://github.com/HimanshuNarware/Devlabs/assets/81490172/b4f9b0fc-fc31-4bb3-81bd-d308af83aadd)

**Comment by HimanshuNarware** [comment]
> Hi, I have added a Share button which when clicked shows an alert saying Link Copied! and the link is copied to the user's clipboard ![image](https://user-images.githubusercontent.com/81490172/271073774-b4f9b0fc-fc31-4bb3-81bd-d308af83aadd.png)

@shreyanshtiwari02 nice, now raise a pr
